sonar.projectKey=TU_PROYECTO_HOSANNA
sonar.organization=TU_ORGANIZACION
sonar.sources=Diseño
# Esto ignora la carpeta Backup para que no te baje el porcentaje por duplicados
sonar.exclusions=Diseño/Backup/**
sonar.javascript.lcov.reportPaths=
